'use strict';
import { JooanAudioClient } from './audio-client.js';
let csrf='', wifiId='', firmwareId='', ptzLease='';
let audioClient=null,unbindTalk=null;
const $=s=>document.querySelector(s);
const notice=m=>{$('#notice').textContent=m;};
async function api(path,options={}){options.headers=Object.assign({'Accept':'application/json'},options.headers||{});if(csrf&&options.method&&options.method!=='GET')options.headers['X-CSRF-Token']=csrf;const r=await fetch(path,options);const type=r.headers.get('content-type')||'';const data=type.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(data.error||data||`HTTP ${r.status}`);return data;}
function show(id){['#login','#setup','#dashboard'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');}
async function status(){const s=await api('/api/v1/status');$('#status').textContent=JSON.stringify(s,null,2);$('#connection').textContent='Connected';if(s.must_change)show('#setup');else show('#dashboard');}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/api/v1/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});csrf=d.csrf;d.must_change?show('#setup'):await load();}catch(x){notice(x.message);}});
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/v1/setup/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});csrf='';show('#login');notice('Password changed. Sign in again.');}catch(x){notice(x.message);}});
async function load(){await status();const [s,m]=await Promise.all([api('/api/v1/streams'),api('/api/v1/network/mdns')]);$('#streams').textContent=s.streams.map(x=>`${x.id}: ${x.width}×${x.height}\n${x.rtsp}`).join('\n\n');$('#mdns-form').elements.hostname.value=m.hostname;$('#mdns-result').textContent=`https://${m.address}/`;try{$('#ssh-list').textContent=JSON.stringify(await api('/api/v1/ssh/authorized-keys'),null,2);}catch(x){$('#ssh-list').textContent=x.message;}}
$('#refresh').onclick=()=>load().catch(x=>notice(x.message));
$('#logout').onclick=async()=>{await api('/api/v1/session',{method:'DELETE'});csrf='';show('#login');};
$('#snapshot-button').onclick=()=>{$('#snapshot').src=`/api/v1/snapshot?t=${Date.now()}`;};
$('#audio-connect').onclick=async()=>{try{if(audioClient){unbindTalk?.();await audioClient.close();audioClient=null;$('#push-to-talk').disabled=true;$('#audio-state').textContent='Disconnected';$('#audio-connect').textContent='Listen';return;}const protocol=location.protocol==='https:'?'wss:':'ws:';audioClient=new JooanAudioClient({url:`${protocol}//${location.host}/api/v1/audio/mic`,authToken:csrf,allowInsecure:location.protocol!=='https:'});audioClient.addEventListener('talkstate',e=>{$('#audio-state').textContent=e.detail.active?'Speaking':'Listening';});audioClient.addEventListener('audioerror',e=>notice(e.detail?.message||'Audio error'));await audioClient.connect();unbindTalk=audioClient.bindPressToTalk($('#push-to-talk'));$('#push-to-talk').disabled=false;$('#audio-state').textContent='Listening';$('#audio-connect').textContent='Disconnect audio';}catch(x){audioClient=null;$('#push-to-talk').disabled=true;notice(x.message);}};
$('#wifi-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/v1/network/wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});wifiId=d.id||'';$('#wifi-result').textContent=JSON.stringify(d,null,2);}catch(x){notice(x.message);}});
$('#wifi-commit').onclick=()=>api('/api/v1/network/wifi',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:wifiId})}).then(x=>$('#wifi-result').textContent=JSON.stringify(x,null,2)).catch(x=>notice(x.message));
$('#wifi-rollback').onclick=()=>api('/api/v1/network/wifi',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:wifiId})}).then(x=>$('#wifi-result').textContent=JSON.stringify(x,null,2)).catch(x=>notice(x.message));
$('#mdns-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/v1/network/mdns',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#mdns-result').textContent=`https://${d.address}/`;}catch(x){notice(x.message);}});
$('#ssh-form').addEventListener('submit',async e=>{e.preventDefault();try{const key=new FormData(e.target).get('key');await api('/api/v1/ssh/authorized-keys',{method:'POST',headers:{'Content-Type':'text/plain'},body:key});await load();}catch(x){notice(x.message);}});
async function ptz(command){if(!ptzLease){const d=await api('/api/v1/ptz/lease',{method:'POST'});ptzLease=d.lease;}if(command==='stop'){await api('/api/v1/ptz/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lease:ptzLease})});ptzLease='';}else await api('/api/v1/ptz/move',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lease:ptzLease,command})});$('#ptz-state').textContent=ptzLease?`Lease active: ${command}`:'Stopped';}
document.querySelectorAll('[data-ptz]').forEach(b=>{if(b.dataset.ptz==='stop'){b.onclick=()=>ptz('stop').catch(x=>{ptzLease='';notice(x.message);});return;}const start=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);ptz(b.dataset.ptz).catch(x=>{ptzLease='';notice(x.message);});};const stop=e=>{e.preventDefault();if(ptzLease)ptz('stop').catch(x=>{ptzLease='';notice(x.message);});};b.addEventListener('pointerdown',start);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('lostpointercapture',stop);});
$('#firmware-form').addEventListener('submit',async e=>{e.preventDefault();const file=new FormData(e.target).get('image');try{const d=await api('/api/v1/update',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});firmwareId=d.id||'';$('#firmware-result').textContent=JSON.stringify(d,null,2);}catch(x){notice(x.message);}});
$('#firmware-apply').onclick=()=>api('/api/v1/update',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:firmwareId})}).then(x=>$('#firmware-result').textContent=JSON.stringify(x,null,2)).catch(x=>notice(x.message));
status().catch(()=>show('#login'));
