'use strict';
import { JooanAudioClient } from './audio-client.js';
import { Fmp4Player } from './video-player.js';
let csrf='', wifiId='', firmwareId='', ptzLease='';
let audioClient=null,unbindTalk=null;
let videoPlayers=[];
const $=s=>document.querySelector(s);
const notice=m=>{$('#notice').textContent=m;};
async function api(path,options={}){options.headers=Object.assign({'Accept':'application/json'},options.headers||{});if(csrf&&options.method&&options.method!=='GET')options.headers['X-CSRF-Token']=csrf;const r=await fetch(path,options);const type=r.headers.get('content-type')||'';const data=type.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(data?.error?.message||data?.error||data||`HTTP ${r.status}`);return data;}
function show(id){['#login','#setup','#dashboard'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');}
async function status(){const s=await api('/api/v1/status');$('#status').textContent=JSON.stringify(s,null,2);$('#connection').textContent='Connected';$('#default-password-warning').classList.toggle('hidden',!s.default_password_warning&&s.ssh_password_sync);if(!s.ssh_password_sync)$('#default-password-warning').textContent='SSH password is not synchronized after upgrade. Change the administrator password once to enable it.';show('#dashboard');return s;}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/api/v1/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});csrf=d.csrf;await load();if(d.default_password_warning)notice('Security warning: the public initial password is still active.');}catch(x){notice(x.message);}});
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/v1/setup/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});csrf='';show('#login');notice('Password changed. Sign in again.');}catch(x){notice(x.message);}});
async function load(){await status();const [s,m]=await Promise.all([api('/api/v1/streams'),api('/api/v1/network/mdns')]);$('#streams').textContent=s.streams.map(x=>`${x.id}: ${x.width}×${x.height}\n${x.rtsp}`).join('\n\n');videoPlayers.forEach(x=>x.close());videoPlayers=s.streams.map(stream=>new Fmp4Player($(`#video-${stream.id}`),stream));videoPlayers.forEach(player=>player.start().catch(x=>notice(`${player.stream.id} video: ${x.message}`)));$('#mdns-form').elements.hostname.value=m.hostname;$('#mdns-result').textContent=`https://${m.address}/`;try{$('#ssh-list').textContent=JSON.stringify(await api('/api/v1/ssh/authorized-keys'),null,2);}catch(x){$('#ssh-list').textContent=x.message;}loadPresets().catch(x=>notice(x.message));}
$('#refresh').onclick=()=>load().catch(x=>notice(x.message));
$('#logout').onclick=async()=>{videoPlayers.forEach(x=>x.close());videoPlayers=[];await api('/api/v1/session',{method:'DELETE'});csrf='';show('#login');};
$('#change-password').onclick=()=>show('#setup');
$('#audio-connect').onclick=async()=>{try{if(audioClient){unbindTalk?.();await audioClient.close();audioClient=null;$('#push-to-talk').disabled=true;$('#audio-state').textContent='Disconnected';$('#audio-connect').textContent='Listen';return;}const protocol=location.protocol==='https:'?'wss:':'ws:';audioClient=new JooanAudioClient({url:`${protocol}//${location.host}/api/v1/audio/mic`,authToken:csrf,allowInsecure:location.protocol!=='https:'});audioClient.addEventListener('talkstate',e=>{$('#audio-state').textContent=e.detail.active?'Speaking':'Listening';});audioClient.addEventListener('audioerror',e=>notice(e.detail?.message||'Audio error'));await audioClient.connect();unbindTalk=audioClient.bindPressToTalk($('#push-to-talk'));$('#push-to-talk').disabled=false;$('#audio-state').textContent='Listening';$('#audio-connect').textContent='Disconnect audio';}catch(x){audioClient=null;$('#push-to-talk').disabled=true;notice(x.message);}};
$('#wifi-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/v1/network/wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});wifiId=d.id||'';$('#wifi-result').textContent=JSON.stringify(d,null,2);}catch(x){notice(x.message);}});
$('#wifi-commit').onclick=()=>api('/api/v1/network/wifi',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:wifiId})}).then(x=>$('#wifi-result').textContent=JSON.stringify(x,null,2)).catch(x=>notice(x.message));
$('#wifi-rollback').onclick=()=>api('/api/v1/network/wifi',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:wifiId})}).then(x=>$('#wifi-result').textContent=JSON.stringify(x,null,2)).catch(x=>notice(x.message));
$('#mdns-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/v1/network/mdns',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#mdns-result').textContent=`https://${d.address}/`;}catch(x){notice(x.message);}});
$('#routes-form').addEventListener('submit',async e=>{e.preventDefault();try{$('#routes-result').textContent=JSON.stringify(await api('/api/v1/network/routes',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}),null,2);}catch(x){notice(x.message);}});
$('#ssh-form').addEventListener('submit',async e=>{e.preventDefault();try{const key=new FormData(e.target).get('key');await api('/api/v1/ssh/authorized-keys',{method:'POST',headers:{'Content-Type':'text/plain'},body:key});await load();}catch(x){notice(x.message);}});
async function ptz(command){if(!ptzLease){const d=await api('/api/v1/ptz/lease',{method:'POST'});ptzLease=d.lease;}if(command==='stop'){await api('/api/v1/ptz/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lease:ptzLease})});ptzLease='';}else await api('/api/v1/ptz/move',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lease:ptzLease,command,duration_ms:500,speed:Number($('#ptz-speed').value)})});$('#ptz-state').textContent=ptzLease?`Lease active: ${command}`:'Stopped';}
document.querySelectorAll('[data-ptz]').forEach(b=>{if(b.dataset.ptz==='stop'){b.onclick=()=>ptz('stop').catch(x=>{ptzLease='';notice(x.message);});return;}const start=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);ptz(b.dataset.ptz).catch(x=>{ptzLease='';notice(x.message);});};const stop=e=>{e.preventDefault();if(ptzLease)ptz('stop').catch(x=>{ptzLease='';notice(x.message);});};b.addEventListener('pointerdown',start);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('lostpointercapture',stop);});
async function operation(accepted){for(let i=0;i<65;i++){const state=await api(accepted.status);if(state.state==='complete')return state.response;await new Promise(ok=>setTimeout(ok,1000));}throw new Error('Camera operation timed out');}
async function loadPresets(){const response=await operation(await api('/api/v1/ptz/presets'));const list=response.ptz_coordinate||response.presets||[];$('#preset-list').replaceChildren(...list.map(item=>{const o=document.createElement('option');o.value=String(item.coordinateID??item.token);o.textContent=item.name||o.value;return o;}));return list;}
$('#ptz-home').onclick=async()=>{try{const presets=await loadPresets();const home=presets.find(x=>x.name==='__home__');if(home)await operation(await api('/api/v1/ptz/home',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'goto',token:Number(home.coordinateID??home.token)})}));else if(window.confirm('No home preset exists. Save the current position as home?'))await operation(await api('/api/v1/ptz/home',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set'})}));notice('Home operation completed');}catch(x){notice(x.message);}};
$('#preset-set').onclick=async()=>{try{const name=window.prompt('Preset name');if(!name)return;await operation(await api('/api/v1/ptz/presets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}));await loadPresets();}catch(x){notice(x.message);}};
$('#preset-goto').onclick=()=>api('/api/v1/ptz/presets',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:Number($('#preset-list').value)})}).then(operation).catch(x=>notice(x.message));
$('#preset-delete').onclick=()=>api('/api/v1/ptz/presets',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:Number($('#preset-list').value)})}).then(operation).then(loadPresets).catch(x=>notice(x.message));
$('#firmware-form').addEventListener('submit',async e=>{e.preventDefault();const file=new FormData(e.target).get('image');try{const d=await api('/api/v1/update',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});firmwareId=d.id||'';$('#firmware-result').textContent=JSON.stringify(d,null,2);}catch(x){notice(x.message);}});
$('#firmware-apply').onclick=()=>api('/api/v1/update',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:firmwareId})}).then(x=>$('#firmware-result').textContent=JSON.stringify(x,null,2)).catch(x=>notice(x.message));
status().catch(()=>show('#login'));
if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('/sw.js').catch(()=>{});
