'use strict';
export class Fmp4Player {
  constructor(video,stream){this.video=video;this.stream=stream;this.media=null;this.buffer=null;this.sequence=0;this.closed=false;this.objectUrl='';}
  async start(){if(!('MediaSource'in window))throw new Error('Media Source Extensions unavailable');const mime=this.stream.mime||'video/mp4; codecs="avc1.640032"';if(!MediaSource.isTypeSupported(mime))throw new Error(`Unsupported codec ${mime}`);this.media=new MediaSource();this.objectUrl=URL.createObjectURL(this.media);this.video.src=this.objectUrl;await new Promise((ok,bad)=>{this.media.addEventListener('sourceopen',ok,{once:true});this.media.addEventListener('error',()=>bad(new Error('MediaSource failed')),{once:true});});this.buffer=this.media.addSourceBuffer(mime);this.buffer.mode='segments';await this.append((await this.fetch(this.stream.init)).bytes);void this.pump();await this.video.play().catch(()=>{});}
  async fetch(url){const r=await window.fetch(url,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error(`video HTTP ${r.status}`);return{bytes:await r.arrayBuffer(),sequence:Number(r.headers.get('X-Joan-Sequence')||0)};}
  append(bytes){if(this.closed||!this.buffer)return Promise.reject(new Error('player closed'));return new Promise((ok,bad)=>{const done=()=>{clean();ok();},fail=()=>{clean();bad(new Error('fragment append failed'));},clean=()=>{this.buffer.removeEventListener('updateend',done);this.buffer.removeEventListener('error',fail);};this.buffer.addEventListener('updateend',done,{once:true});this.buffer.addEventListener('error',fail,{once:true});this.buffer.appendBuffer(bytes);});}
  async pump(){while(!this.closed){try{const sep=this.stream.fragment.includes('?')?'&':'?';const part=await this.fetch(`${this.stream.fragment}${sep}after=${this.sequence}`);if(!part.sequence||part.sequence<=this.sequence)throw new Error('stale fragment');await this.append(part.bytes);this.sequence=part.sequence;if(this.buffer.buffered.length){const end=this.buffer.buffered.end(this.buffer.buffered.length-1);if(end-this.video.currentTime>8)this.video.currentTime=Math.max(0,end-2);if(!this.buffer.updating&&this.buffer.buffered.start(0)<end-30){this.buffer.remove(0,end-10);await new Promise(ok=>this.buffer.addEventListener('updateend',ok,{once:true}));}}}catch(_){if(!this.closed)await new Promise(ok=>setTimeout(ok,1000));}}}
  close(){this.closed=true;try{if(this.media?.readyState==='open')this.media.endOfStream();}catch(_){}this.video.removeAttribute('src');this.video.load();if(this.objectUrl)URL.revokeObjectURL(this.objectUrl);}
}
